### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aqw** [G-Node/logOS#2]
I am planning to use the Gin logo on the (soon to be relaunched) StudyForrest website --- to credit Gin for hosting the project's datasets.

I'm currently building the copyright page, marking the licenses of all assets, and crediting authors.

I have been unable to find the license for the artwork in this repo. Could you please clarify what they're released under?

**Comment by mpsonntag** [comment]
Very good question. I'll investigate and upload a License as soon as possible. Thanks for giving credit!

**Comment by aqw** [comment]
Thanks for looking into this!

**Comment by mpsonntag** [comment]
Please bear with us, we need to check with the artists creating the logos...

**Comment by aqw** [comment]
No worries. Thanks for the followup. :-)

**Comment by mpsonntag** [comment]
I finally got copyright and license information for the GIN logo:

The License is [CC-by](https://creativecommons.org/licenses/by/4.0/), the copyright is
```
(c) 2017 Christian Spalthoff and German Neuroinformatics Node
```

Sorry for the long wait, I hope this information suffices.

**Comment by aqw** [comment]
This is all the information I need. Thank you!
